# Generated by Django 5.1.7 on 2025-10-01 13:06

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckItemDict",
            fields=[
                (
                    "item_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="考核细则ID"
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="考核细则名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "考核项字典",
                "verbose_name_plural": "考核项字典",
                "db_table": "t_check_item_dict",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "company_id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="公司代码",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=50, verbose_name="公司名称"),
                ),
                (
                    "legal_representative",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="法人代表"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="所在区域"
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="银行账号"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "satisfaction",
                    models.SmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="满意度",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户单位",
                "verbose_name_plural": "客户单位",
                "db_table": "t_company",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="产品编码",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=50, verbose_name="产品名称"),
                ),
                (
                    "product_status",
                    models.SmallIntegerField(
                        choices=[(1, "常规产品"), (2, "新品")],
                        default=1,
                        verbose_name="产品状态",
                    ),
                ),
                (
                    "product_desc",
                    models.TextField(blank=True, null=True, verbose_name="产品描述"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "产品",
                "verbose_name_plural": "产品",
                "db_table": "t_product",
            },
        ),
        migrations.CreateModel(
            name="Salesman",
            fields=[
                (
                    "salesman_id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="销售员编码(唯一标识)",
                    ),
                ),
                (
                    "salesman_name",
                    models.CharField(max_length=20, verbose_name="销售员姓名"),
                ),
                (
                    "contact_info",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="联系方式(电话)",
                    ),
                ),
                (
                    "dept",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="所属部门(如销售一部)",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "销售员",
                "verbose_name_plural": "销售员",
                "db_table": "t_salesman",
            },
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "complaint_id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="投诉单编号",
                    ),
                ),
                (
                    "related_order_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="关联订单编号",
                    ),
                ),
                ("complaint_content", models.TextField(verbose_name="投诉内容")),
                (
                    "complaint_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="投诉时间"
                    ),
                ),
                (
                    "complaint_status",
                    models.SmallIntegerField(
                        choices=[(0, "待处理"), (1, "处理中"), (2, "已结案")],
                        default=0,
                        verbose_name="投诉状态",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="backend.company",
                        verbose_name="关联客户单位",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户投诉",
                "verbose_name_plural": "客户投诉",
                "db_table": "t_complaint",
            },
        ),
        migrations.CreateModel(
            name="NewProductFeedback",
            fields=[
                (
                    "feedback_id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="新品反馈编号",
                    ),
                ),
                (
                    "feedback_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="反馈评分"
                    ),
                ),
                (
                    "feedback_content",
                    models.TextField(blank=True, null=True, verbose_name="反馈内容"),
                ),
                (
                    "feedback_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="反馈时间"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="backend.company",
                        verbose_name="关联反馈客户",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="backend.product",
                        verbose_name="关联新品",
                    ),
                ),
            ],
            options={
                "verbose_name": "新品市场反馈",
                "verbose_name_plural": "新品市场反馈",
                "db_table": "t_new_product_feedback",
            },
        ),
        migrations.CreateModel(
            name="QualityCheck",
            fields=[
                (
                    "check_id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="考核单编号",
                    ),
                ),
                ("check_time", models.DateTimeField(verbose_name="考核时间")),
                (
                    "is_archived",
                    models.SmallIntegerField(
                        choices=[(0, "未存档"), (1, "已存档")],
                        default=0,
                        verbose_name="存档状态",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "check_items",
                    models.ManyToManyField(
                        to="backend.checkitemdict", verbose_name="考核内容"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="backend.company",
                        verbose_name="关联客户单位",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="backend.product",
                        verbose_name="关联产品",
                    ),
                ),
                (
                    "checker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="backend.salesman",
                        verbose_name="考核人员ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "服务质量检查考核单",
                "verbose_name_plural": "服务质量检查考核单",
                "db_table": "t_quality_check",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="订单编号",
                    ),
                ),
                ("order_date", models.DateField(verbose_name="购买日期")),
                (
                    "order_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="订单金额",
                    ),
                ),
                (
                    "order_status",
                    models.SmallIntegerField(
                        choices=[(1, "已完成"), (2, "待交付"), (3, "已取消")],
                        default=1,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="backend.company",
                        verbose_name="关联公司",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="backend.product",
                        verbose_name="关联购买产品",
                    ),
                ),
                (
                    "salesman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="backend.salesman",
                        verbose_name="关联负责销售员",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "db_table": "t_order",
            },
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "training_id",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="培训计划编号",
                    ),
                ),
                (
                    "training_topic",
                    models.CharField(max_length=255, verbose_name="培训主题"),
                ),
                (
                    "training_type",
                    models.IntegerField(
                        choices=[(1, "内部培训"), (2, "外部培训")],
                        verbose_name="培训类型",
                    ),
                ),
                ("training_time", models.DateTimeField(verbose_name="培训时间")),
                (
                    "training_status",
                    models.IntegerField(
                        choices=[(0, "未开始"), (1, "进行中"), (2, "已结束")],
                        default=0,
                        verbose_name="培训状态",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="backend.company",
                        verbose_name="外部培训单位",
                    ),
                ),
                (
                    "salesman",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="backend.salesman",
                        verbose_name="内部培训",
                    ),
                ),
            ],
            options={
                "verbose_name": "培训计划",
                "verbose_name_plural": "培训计划",
                "db_table": "training",
            },
        ),
    ]
