# Generated by Django 5.1.7 on 2025-10-04 10:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_company_create_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "file_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(default="技术文档", max_length=40)),
                ("file", models.FileField(upload_to="uploads/")),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="文档描述"),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "文件路径",
                "verbose_name_plural": "文件路径",
                "db_table": "t_file",
            },
        ),
    ]
