# Generated by Django 5.1.7 on 2025-10-04 16:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_uploadedfile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkitemdict",
            options={"verbose_name": "服务项字典", "verbose_name_plural": "服务项字典"},
        ),
        migrations.AlterField(
            model_name="checkitemdict",
            name="item_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="服务细则ID"
            ),
        ),
        migrations.AlterField(
            model_name="checkitemdict",
            name="item_name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="服务细则名称"
            ),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "check_id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="服务单编号",
                    ),
                ),
                ("check_time", models.DateTimeField(verbose_name="服务时间")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "check_items",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.checkitemdict",
                        verbose_name="服务内容",
                    ),
                ),
                (
                    "checker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="backend.salesman",
                        verbose_name="服务人员ID",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="backend.company",
                        verbose_name="关联客户单位",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="backend.product",
                        verbose_name="关联产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "服务质量检查考核单",
                "verbose_name_plural": "服务质量检查考核单",
                "db_table": "t_service",
            },
        ),
        migrations.DeleteModel(
            name="QualityCheck",
        ),
    ]
