# Generated by Django 5.1.7 on 2025-10-04 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_checkitemdict_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="cost_time",
            field=models.DurationField(
                default=datetime.timedelta(seconds=7200), verbose_name="服务时长"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="service_status",
            field=models.IntegerField(
                choices=[(0, "未开始"), (1, "进行中"), (2, "已结束")],
                default=0,
                verbose_name="服务状态",
            ),
        ),
    ]
