# Generated by Django 5.1.7 on 2025-10-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_service_cost_time_service_service_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_status",
            field=models.IntegerField(
                choices=[(0, "未开始"), (1, "进行中"), (2, "已完成")],
                default=0,
                verbose_name="服务状态",
            ),
        ),
    ]
