# Generated by Django 5.1.7 on 2025-10-05 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_alter_service_service_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="related_order_id",
        ),
        migrations.AddField(
            model_name="complaint",
            name="related_order",
            field=models.ForeignKey(
                default="O001",
                on_delete=django.db.models.deletion.RESTRICT,
                to="backend.order",
                verbose_name="关联订单",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="complaint",
            name="salesman",
            field=models.ForeignKey(
                default="S001",
                on_delete=django.db.models.deletion.RESTRICT,
                to="backend.salesman",
                verbose_name="处理人",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="complaint",
            name="complaint_status",
            field=models.SmallIntegerField(
                choices=[(0, "待处理"), (1, "处理中"), (2, "已完成")],
                default=0,
                verbose_name="投诉状态",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="checker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="backend.salesman",
                verbose_name="服务人员",
            ),
        ),
    ]
