# Generated by Django 5.1.7 on 2025-10-05 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_remove_complaint_related_order_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="related_order",
        ),
        migrations.AddField(
            model_name="complaint",
            name="product",
            field=models.ForeignKey(
                default="P001",
                on_delete=django.db.models.deletion.RESTRICT,
                to="backend.product",
                verbose_name="关联产品",
            ),
            preserve_default=False,
        ),
    ]
