# Generated by Django 5.1.7 on 2025-10-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_remove_complaint_related_order_complaint_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newproductfeedback",
            name="feedback_score",
        ),
        migrations.AddField(
            model_name="newproductfeedback",
            name="feedback_type",
            field=models.SmallIntegerField(
                choices=[(1, "正面反馈"), (2, "负面反馈")],
                default=1,
                verbose_name="反馈类型",
            ),
        ),
    ]
